create table if not exists CORRECTION_FACTORS as from read_csv('./sample_data/src/CORRECTION_FACTORS.csv') ;
create table if not exists TIME_SERIES_DATASETS as from read_csv('./build/time_series_datasets.csv') ;

COPY(
    SELECT CORRECTION_FACTORS.*, TIME_SERIES_DATASETS.TIMESERIES_ID
    FROM CORRECTION_FACTORS 
    INNER JOIN TIME_SERIES_DATASETS ON
        CORRECTION_FACTORS.SITE_ID=TIME_SERIES_DATASETS.SITE_ID AND 
        CORRECTION_FACTORS.VARIABLE=TIME_SERIES_DATASETS.PARAMETER_ID AND
        TIME_SERIES_DATASETS.PROCESSING_LEVEL=1
) TO './build/correction_configurations.csv' (HEADER, DELIMITER ',') ;