create table if not exists VARIABLE_INSTRUMENTATION as from read_csv('./sample_data/src/VARIABLE_INSTRUMENTATION.csv') ;
create table if not exists TIMESERIES as from read_csv('./sample_data/src/TIMESERIES.csv') ;
COPY(
    SELECT DISTINCT 
        VARIABLE_INSTRUMENTATION.INSTRUMENT_ID as INSTRUMENT_ID,
        VARIABLE_INSTRUMENTATION.VARIABLE_NAME as VARIABLE_ID
    FROM TIMESERIES
    INNER JOIN VARIABLE_INSTRUMENTATION 
        ON TIMESERIES.PARAMETER_ID=VARIABLE_INSTRUMENTATION.VARIABLE_NAME
) TO './build/monitoring_system_variables.csv';