create table IF NOT EXISTS PARAMETER_RANGES_QC as from read_csv('./sample_data/src/PARAMETER_RANGES_QC.csv', AUTO_DETECT=true) ;
create table if not exists TIME_SERIES_DATASETS as from read_csv('./build/time_series_datasets.csv') ;

COPY(
SELECT DISTINCT PARAMETER_RANGES_QC.*, TIME_SERIES_DATASETS.TIMESERIES_ID
FROM PARAMETER_RANGES_QC 
INNER JOIN TIME_SERIES_DATASETS on PARAMETER_RANGES_QC.PARAMETER_ID == TIME_SERIES_DATASETS.PARAMETER_ID AND PARAMETER_RANGES_QC.SITE_ID == TIME_SERIES_DATASETS.SITE_ID AND TIME_SERIES_DATASETS.PROCESSING_LEVEL == 1
) TO './build/qc_range_configuration_items.csv'(HEADER, DELIMITER ',') ;