create table IF NOT EXISTS PARAMETER_RANGES_QC as from read_csv('./src/PARAMETER_RANGES_QC.csv', AUTO_DETECT=true) ;
create table IF NOT EXISTS PARAMETERS as from read_csv('./src/PARAMETERS.csv', AUTO_DETECT=true) ;

COPY(
SELECT DISTINCT PARAMETER_RANGES_QC.* FROM PARAMETER_RANGES_QC LEFT OUTER JOIN PARAMETERS on PARAMETER_RANGES_QC.PARAMETER_ID == PARAMETERS.PARAMETER_ID
WHERE PARAMETERS.PARAMETER_ID IS NOT NULL
) TO './build/qc_range_configuration_items.csv'(HEADER, DELIMITER ',') ;