CREATE TABLE IF NOT EXISTS SI AS FROM read_csv('./sample_data/src/SITE_INSTRUMENTATION.csv', AUTO_DETECT=true) ;
CREATE TABLE IF NOT EXISTS SS AS FROM read_csv('./sample_data/src/SENSOR_SLOT_IDS.csv', AUTO_DETECT=true) ;
CREATE TABLE IF NOT EXISTS TS AS FROM read_csv('./sample_data/src/TIMESERIES_IDS.csv', AUTO_DETECT=true) ;

COPY (
    SELECT SI.*, SS.INSTRUMENT_ID, TS.PARAMETER_ID
    FROM
    SI
    LEFT JOIN SS on SI.SENSOR_SLOT_ID = SS.SENSOR_SLOT_ID
    LEFT JOIN TS on SI.SENSOR_SLOT_ID = TS.SENSOR_SLOT_ID AND SI.SITE_ID = TS.SITE_ID
) TO './build/sensor_deployments.csv' (HEADER, DELIMITER ',') ;
