create table if not exists FIRMWARE_HISTORY as from read_csv('./sample_data/src/Firmware_history.csv', AUTO_DETECT=true) ;
COPY(
    SELECT 
        ID, INSTRUMENT_ID, SERIAL_NUMBER, FIRMWARE, 
        COALESCE(START_DATETIME, '2000-01-01T00:00:00:00.000Z') AS START_DATETIME,
        COALESCE(
            END_DATETIME,
            (SELECT START_DATETIME FROM FIRMWARE_HISTORY WHERE SERIAL_NUMBER==x.SERIAL_NUMBER AND START_DATETIME > x.START_DATETIME ORDER BY START_DATETIME LIMIT 1)
        ) AS END_DATETIME
    FROM FIRMWARE_HISTORY x
    WHERE INSTRUMENT_ID != 'MODEM_PRO'
    ORDER BY SERIAL_NUMBER, START_DATETIME
) TO './build/sensor_firmware_configurations.csv' (HEADER, DELIMITER ',');