create table TIMESERIES as from read_csv('./src/TIMESERIES.csv', AUTO_DETECT=true);
CREATE TABLE ID AS FROM read_csv('./src/intervalDuration.csv', AUTO_DETECT=true) ;

COPY(
SELECT TIMESERIES_ID,
    REGEXP_REPLACE(
        TIMESERIES_ID,
        '_(RAW|LEVEL2(_MEAN)?|LEVEL3|1DAY(_9TO9)?|TOTAL|SIMPLE)',
        '', 'g') AS VARIABLE_NAME,
    CASE
        WHEN TABLE_NAME ^@ 'LEVEL1' THEN 1
        WHEN TABLE_NAME ^@ 'LEVEL2' THEN 2
        WHEN TABLE_NAME ^@ 'LEVEL3' THEN 3
    END as PROCESSING_LEVEL,
    TIMESERIES_NAME,
    ID.DURATION as DURATION
FROM TIMESERIES
JOIN ID on TIMESERIES.INTERVAL_ID=ID.INTERVAL_ID

) TO './build/timeSeriesProperty.csv' (HEADER, DELIMITER ',') ;
