CREATE TABLE IF NOT EXISTS TS AS FROM read_csv('./sample_data/src/TIMESERIES.csv', AUTO_DETECT=true) ;
CREATE TABLE IF NOT EXISTS ID AS FROM read_csv('./sample_data/src/intervalDuration.csv', AUTO_DETECT=true) ;
CREATE TABLE IF NOT EXISTS TIMESERIES_S3 AS FROM read_csv('./sample_data/src/TIMESERIES_S3_MAP_REFINED.csv', AUTO_DETECT=true) ;

COPY (
    SELECT 
    TS.*,
    ID.DURATION,
    TIMESERIES_S3.S3_BUCKET,
    TIMESERIES_S3.S3_DATASET,
    TIMESERIES_S3.COLUMN_NAME as S3_COLUMN_NAME,
    CASE 
        WHEN TS.TABLE_NAME ^@ 'LEVEL1' THEN 1
        WHEN TS.TABLE_NAME ^@ 'LEVEL2' THEN 2
        WHEN TS.TABLE_NAME ^@ 'LEVEL3' THEN 3
    END as PROCESSING_LEVEL,
    FROM TS
    JOIN ID on TS.INTERVAL_ID=ID.INTERVAL_ID
    JOIN TIMESERIES_S3 on TIMESERIES_S3.TIMESERIES_ID=TS.TIMESERIES_ID
) TO './build/time_series_definitions.csv'