name: publish model documentation
on:
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4